language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: hCddMWdTteqSjgQBsrVuAaPewpBDqSt2MyHt7fStxAQzQ7rJLggElw4Y2MhRASZ0INYxOgYbaze5sbPhArdrpB0Xc0lSF1NZ7PFWGH1ot9axZEnDGTqav0+O/Wnl78a8DzAmcAaJ8qxBXLnYxcjRBrc/mdCXQW5y9w4f6CnY1iw=
before_script:
- npm install -g grunt-cli
- npm install -g bower
script:
- grunt build
after_success:
- bash deploy.sh
deploy:
  provider: releases
  api_key:
    secure: D/sK1W0oY96ZFnTyF3KnEZSjfVeUxXy7luJHYDkZaLQOIht7uQ4BRfhAihhjOe7rAdoNCVhkkRH+q/xhxnOg5sBOZE44om9jDvEZDstkvqCtTq51RuxRjgdrJg8ZWvjD/GW6+SKjrvO5XP9rn1qMevX3zdq8jaERjDu+RMJ5TRY=
  file:
  - dist/cmdr.js
  - dist/cmdr.min.js
  - dist/cmdr.css
  - dist/cmdr.min.css
  skip_cleanup: true
  on:
    tags: true
    repo: shaftware/cmdrjs
